version: "3"
services:
  python_scraping_template:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: python_scraping_template-image
    container_name: python_scraping_template-container
    tty: true
