version: "3"
services:
  python_scraping_test:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: python_scraping_test-image
    container_name: python_scraping_test-container
    tty: true
